export const TopCategoryMenubar = "https://my.careerera.com/API/course/TopCategoryMenubar.php"
export const CategoryPage = "https://my.careerera.com/API/course/CategoryPage.php?url="
export const EsCategoryPage = "https://es.careerera.com/API/course/CategoryPage.php?url="
export const FreeElearningBatch = "https://my.careerera.com/API/course/FreeElearningBatch.php?timeZone="
export const AllBatchList = "https://my.careerera.com/API/course/AllBatchList.php?timeZone="
export const CountryList = "https://my.careerera.com/API/common/CountryList.php"
export const world_citys= "https://my.careerera.com/API/common/world_citys.php?id="
export const world_countries = "https://my.careerera.com/API/common/world_countries.php"
export const world_state = "https://my.careerera.com/API/common/world_state.php?id="
export const city1 = "https://my.careerera.com/admin/admins/api/city1.php?service="
export const state1 = "https://my.careerera.com/admin/admins/api/state1.php?service="
export const county1 = "https://my.careerera.com/admin/admins/api/county1.php?service="
export const query = "https://my.careerera.com/admin/curl_All_enqery.php"
export const HomepageComment = " https://my.careerera.com/API/course/HomepageComment.php"
export const Youtube = " https://my.careerera.com/API/common/reviewlinks.php"
export const Zip = "https://my.careerera.com/admin/admins/api/zip.php?service="
export const HomepageCounter = "https://my.careerera.com/API/course/HomepageCounter.php "
export const BlogList = "https://es.careerera.com/API/common/BlogList.php"
export const CategoryList = "http://my.careerera.com/API/course/CategoryList.php"
export const BatchDetails = "https://my.careerera.com/API/course/BatchDetails.php?BId="
export const batch_location= "https://my.careerera.com/API/common/batch_location.php"
export const ar_blog_list = "https://my.careerera.com/API/common/ar-blogList.php"
export const escoursoslist= "https://es.careerera.com/API/course/CourseList.php?Language=2"
export const esBatchList = "https://es.careerera.com/API/course/AllBatchList.php?Language=2&timeZone="
export const esBlogList = "https://es.careerera.com/API/common/BlogList.php"
export const esBlogDetail= "https://es.careerera.com/API/common/BlogDetails.php?Url="
export const arBlogDetail= "https://my.careerera.com/API/common/arBlogDetails.php?Url="
export const cityDetailCyber= "https://my.careerera.com/admin/admins/api/cityDetail.php?service=cyber-security&state="
export const stateDetailCyber= "https://my.careerera.com/admin/admins/api/statesDetail.php?service=cyber-security&state="
export const countyDetailCyber= "https://my.careerera.com/admin/admins/api/countyDetail.php?service=cyber-security&state="
export const cityDetailData= "https://my.careerera.com/admin/admins/api/cityDetail.php?service=data-science&state="
export const stateDetailData= "https://my.careerera.com/admin/admins/api/statesDetail.php?service=data-science&state="
export const countyDetaildata= "https://my.careerera.com/admin/admins/api/countyDetail.php?service=data-science&state="
export const JObData = "http://jobs.snva.com/api/jobs?api_token=Nxo9A8Koga6hVuTfEWeEBZNbK5OeJYYauuEH6Q9s3Gd9JuMea7XjprMtI4L1"
export const AboutProgram ="https://my.careerera.com/API/course/AboutCourse.php?course_url="
export const Eventslist = "https://my.careerera.com/API/common/EventsList.php"
export const Eventslist1 = "https://my.careerera.com/API/common/EventsList.php"
export const EventDetails= "https://my.careerera.com/API/common/EventsDetails.php?Url="
export const BlogListS= "https://my.careerera.com/API/common/BlogList.php"
export const BlogDetailS= "https://my.careerera.com/API/common/BlogDetails.php?Url="
export const world_countrieS= "https://my.careerera.com/API/common/world_countries.php?url="